services:
  relink:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    environment:
      - BASE_URL=http://localhost:8080
      - SECRET_KEY=secret
    ports:
      - "8080:8080"
