name: Build and Test

on:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test_and_build_go_project:
    name: Build, Test and Build Image for ${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.22

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: '3.22.0'
      - name: Build Flutter project
        run: |
          pushd web
          flutter pub get
          flutter analyze
          flutter build web

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.version }}
      - name: Test and Build Go project
        run: |
          go test ./...
          go build -ldflags "-w -s" -o relink cmd/relink/main.go

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          file: deployments/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
